/* DO NOT EDIT THIS FILE - it is machine generated */
#include <ScreenCapturer.h>
/* Header for class com_quickblox_screencapturer_sharing_ScreenCapturer */

/*
 * Class:     com_quickblox_screencapturer_sharing_ScreenCapturer_NativeObserver
 * Method:    nativeCapturerStarted
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_quickblox_screencapturer_sharing_ScreenCapturer_00024NativeObserver_nativeCapturerStarted
  (JNIEnv* env, jobject j_object, jlong j_long, jboolean j_boolean){
}

/*
 * Class:     com_quickblox_screencapturer_sharing_ScreenCapturer_NativeObserver
 * Method:    nativeOnFrameCaptured
 * Signature: (J[BIIIJ)V
 */
JNIEXPORT void JNICALL Java_com_quickblox_screencapturer_sharing_ScreenCapturer_00024NativeObserver_nativeOnFrameCaptured
  (JNIEnv* env, jobject, jlong, jbyteArray, jint, jint, jint, jlong);

/*
 * Class:     com_quickblox_screencapturer_sharing_ScreenCapturer_NativeObserver
 * Method:    nativeOnOutputFormatRequest
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_com_quickblox_screencapturer_sharing_ScreenCapturer_00024NativeObserver_nativeOnOutputFormatRequest
  (JNIEnv* env, jobject, jlong, jint, jint, jint);


